# Generated by Django 5.1.8 on 2025-04-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='生产厂商全称')),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True, verbose_name='简称')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='上市许可持有人全称')),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True, verbose_name='简称')),
            ],
        ),
        migrations.CreateModel(
            name='Type1Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='一级分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Type2Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='二级分类名称')),
                ('type1_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syyb.type1drug', verbose_name='所属一级分类')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255, verbose_name='药品名')),
                ('trade_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('trade_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名（英文）')),
                ('is_medical_insurance', models.BooleanField(default=False, verbose_name='医保')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='收录类别')),
                ('specification', models.CharField(blank=True, max_length=255, null=True, verbose_name='规格')),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='剂型')),
                ('administration_route', models.CharField(blank=True, max_length=100, null=True, verbose_name='给药途径')),
                ('active_ingredient', models.CharField(blank=True, max_length=255, null=True, verbose_name='活性成分')),
                ('active_ingredient_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='活性成分（英文）')),
                ('approval_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='批准文号')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='批准日期')),
                ('atc_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='ATC代码')),
                ('market_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='上市销售状况')),
                ('drug_image', models.FileField(blank=True, null=True, upload_to='drug_images/', verbose_name='药品图片')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syyb.manufacturer', verbose_name='生产厂商')),
                ('manufacturer_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syyb.manufacturerholder', verbose_name='上市许可持有人')),
                ('type2_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syyb.type2drug', verbose_name='二级分类')),
            ],
            options={
                'verbose_name': '药品信息',
                'verbose_name_plural': '药品信息',
            },
        ),
    ]
