# Generated by Django 5.1.8 on 2025-04-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syyb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='family_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='家庭常用清单'),
        ),
    ]
