# Generated by Django 5.1.8 on 2025-04-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syyb', '0002_drug_family_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='is_medical_insurance',
        ),
        migrations.AddField(
            model_name='drug',
            name='medical_insurance',
            field=models.CharField(max_length=255, null=True, verbose_name='医保'),
        ),
    ]
