# Generated by Django 5.2.9 on 2026-01-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syyb', '0003_remove_drug_is_medical_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='drug_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='药品名（英文）'),
        ),
        migrations.AddField(
            model_name='drug',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否为热门药品'),
        ),
        migrations.AddField(
            model_name='drug',
            name='jd_url',
            field=models.TextField(blank=True, null=True, verbose_name='京东链接'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='atc_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ATC代码'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_image',
            field=models.ImageField(blank=True, null=True, upload_to='drug_images/', verbose_name='药品图片'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type2_drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syyb.type2drug', verbose_name='二级分类'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='生产厂商全称'),
        ),
        migrations.AlterField(
            model_name='manufacturerholder',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='上市许可持有人全称'),
        ),
        migrations.AlterField(
            model_name='type1drug',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='一级分类名称'),
        ),
        migrations.AlterUniqueTogether(
            name='type2drug',
            unique_together={('name', 'type1_drug')},
        ),
    ]
